---
- name: apache-reload
  service: name=apache2 state=reloaded
- name: apache-restart
  service: name=apache2 state=restarted

- name: nginx-reload
  service: name=nginx state=reloaded
- name: nginx-restart
  service: name=nginx state=restarted

- name: supervisor-reload
  service: name=supervisor state=reloaded
- name: supervisor-restart
  service: name=supervisor state=restarted

- name: modoboa-restart
  supervisorctl: name={{ modoboa_name | default('modoboa') }} state=restarted

- name: postfix-reload
  service: name=postfix state=reloaded
- name: postfix-restart
  service: name=postfix state=restarted

- name: dovecot-reload
  service: name=dovecot state=reloaded
- name: dovecot-restart
  service: name=dovecot state=restarted

- name: vsftpd-reload
  service: name=vsftpd state=reloaded
- name: vsftpd-restart
  service: name=vsftpd state=restarted