---
- name: install Apache
  apt: name=apache2 state=present

- name: install modules for Apache
  apt: name={{ item }} state=present
  with_items: 
    - libapache2-mod-php5
  notify: apache-reload

- name: start Apache
  service: name=apache2 state=running enabled=yes

- name: copy ports.conf
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: apache-restart

- name: copy default conf
  template: src=000-default.conf.j2 dest=/etc/apache2/sites-available/000-default.conf
  notify: apache-reload

- name: copy default ssl conf
  template: src=000-default-ssl.conf.j2 dest=/etc/apache2/sites-available/000-default-ssl.conf
  notify: apache-reload

- name: enable default sites
  file: 
    path=/etc/apache2/sites-enabled/{{ item }} 
    src=../sites-available/{{ item }}
    state=link
  with_items:
    - 000-default.conf
    - 000-default-ssl.conf
  notify: apache-reload