---
- name: Update apt cache
  apt: update_cache=yes

- name: install sysadmin utilities
  apt: name={{ item }} state=present
  with_items:
    - htop
    - vim

- name: install dependencies of ansible modules
  apt: name={{ item }} state=present
  with_items:
    - python-pip # pip module
    - python-mysqldb # mysql_*

- name: install virtualenv
  pip: name={{ item }} state=present
  with_items:
    - virtualenv
    - virtualenvwrapper