---
- name: Install components
  apt: name={{ item }} state=present
  with_items:
    - postfix
    - postfix-mysql
    #- postfix-doc
    - mysql-client
    - mysql-server
    - dovecot-common
    - dovecot-imapd
    - dovecot-pop3d
    - postfix
    - libsasl2-2
    - libsasl2-modules
    - libsasl2-modules-sql
    - sasl2-bin
    - libpam-mysql
    - openssl
    - telnet
    - mailutils
- name: Create database for mail admin
  mysql_db: name=mail state=present collation=utf8_general_ci

- name: Create a database user for mail
  mysql_user: name=mail password=mail priv=*.*:ALL host=localhost state=present

- name: Copy sql create script
  copy: src=mail.sql dest=/tmp/dump.sql

- name: Run mail.sql
  shell: cat /tmp/dump.sql | mysql -u mail -pmail mail

- name: Copy virtual domains config
  copy: src=mysql-virtual_domains.cf dest=/etc/postfix/mysql-virtual_domains.cf