---
- name: install nginx
  apt: name=nginx state=present

- name: copy config
  copy: src=bridts dest=/etc/nginx/sites-available/bridts
  notify: nginx-reload

- name: start nginx
  service: name=nginx state=running enabled=yes

- name: make symlink
  file:
    path=/etc/nginx/sites-enabled/bridts 
    src=/etc/nginx/sites-available/bridts
    state=link
  notify: nginx-reload

- name: delete default config link
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify: nginx-reload
