---
- hosts: controller
  roles:
   - ansible_galaxy
  gather_facts: no

- hosts: vagrant
  sudo: yes
  roles:
    - common
    - apache
    - web
    - database
    - modoboa
    - phpmyadmin
  handlers:
    - include: handlers/main.yml
