---
- hosts: controller
  roles:
    - ansible_galaxy

- hosts: vagrant
  roles:
    - common
    - apache
    - web
    - database
    - kosssi.composer
    - phpmyadmin
  handlers:
    - include: handlers/main.yml
  vars:
    - include: vars/main.yml
