---

galaxy_info:
  author: kosssi
  description: Install and Update Composer PHP Dependency Manager
  license: license MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
    - packaging
    - web
    - php
    - composer
